# Generated by Django 6.0.2 on 2026-03-04 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Banco'),
        ),
        migrations.AlterField(
            model_name='banco',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bancos', to='core.usuario'),
        ),
        migrations.AlterField(
            model_name='cartaodecredito',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cartoes', to='core.banco'),
        ),
        migrations.AlterField(
            model_name='cartaodecredito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cartoes_credito', to='core.usuario'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], default='DESPESA', max_length=10),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='categorias', to='core.usuario'),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contas', to='core.banco'),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contas_bancarias', to='core.usuario'),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Atual'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transacoes', to='core.contabancaria'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transacoes', to='core.usuario'),
        ),
    ]
